name: Panuozzo Front Actions
on:
  push:
    branches: [ master ]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

jobs:
  init:
    runs-on: ubuntu-latest
    outputs:
      AWS_S3_BUCKET_NAME: ${{ steps.setvars.outputs.AWS_S3_BUCKET_NAME }}
      AWS_CLOUDFRONT_ID: ${{ steps.setvars.outputs.AWS_CLOUDFRONT_ID }}
    steps:
      - name: Cancel previous workflow
        uses: styfle/cancel-workflow-action@0.4.0
        with:
          access_token: ${{ github.token }}
      - name: Set branch environment variables
        id: setvars
        run: |
          echo "::set-output name=AWS_S3_BUCKET_NAME::main-panuozzo-cl"
          echo "::set-output name=AWS_CLOUDFRONT_ID::EEF0CLCTSXT4T"
  build:
    runs-on: ubuntu-latest
    needs: init
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}
      - name: Build
        run: |
          npm install
          npm run build
      - uses: kersvers/s3-sync-with-cloudfront-invalidation@v1.0.0
        with:
          args: --acl public-read --follow-symlinks --delete
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_S3_BUCKET: ${{ needs.init.outputs.AWS_S3_BUCKET_NAME }}
          DISTRIBUTION_ID: ${{ needs.init.outputs.AWS_CLOUDFRONT_ID }}
          AWS_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
          SOURCE_DIR: ./out
