name: Panuozzo Front Actions
on:
  push:
    branches: [ master ]
    paths-ignore:
      - "README.md"
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_S3_BUCKET_NAME: main-panuozzo-cl
      AWS_S3_BUCKET_REGION: us-east-1
      AWS_CLOUDFRONT_ID: EEF0CLCTSXT4T
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Build
        run: |
          npm install
          npm run build
      - name: Deploy
        uses: lbertenasco/s3-deploy@v1
        with:
          folder: out
          bucket: ${{ secrets.AWS_S3_BUCKET_NAME }}
          dist-id: ${{ secrets.AWS_CLOUDFRONT_ID }}
          invalidation: /*
